Lesson 2
Alyona-GS/JavaScript pull request #2
Opened 2022-06-25 22:24 UTC by Alyona-GS

2022-06-26 21:01 UTC, PonomareVlad requested changes
Нужно уточнить логику решения **2** задачи + опционально проверить решение задач **1** и **8**

2022-06-26 21:01 UTC, PonomareVlad commented on lesson_2/text_to_words.js
> +}
[Результат теста строки на кириллице](https://thinknetica.ponomarevlad.ru/2/1.html?url=https%3A%2F%2Fraw.githubusercontent.com%2FAlyona-GS%2FJavaScript%2Flesson_2%2Flesson_2%2Ftext_to_words.js&func=textToWords#cyrillic)

2022-06-26 21:01 UTC, PonomareVlad commented on lesson_2/compare_array.js
> +};
Можете описать, какое применение у этой функции ?

Как я понял, эта функция возвращает результаты проверки, являются ли числовые элементы первого массива больше, чем соответствующие элементы второго ?

2022-06-26 21:01 UTC, PonomareVlad commented on lesson_2/sortDesc.js
> +}
Такую простую _callback_ функцию можно не выносить отдельно, а определить сразу в аргументах:

```suggestion
const sortDesc = function(numbers) {
  return numbers.sort((a, b) => b - a)
}
```

2022-06-26 21:01 UTC, PonomareVlad commented on lesson_2/employees.js
> +const filterBySalaryAge = employees.filter(filterCallBack);
Полагаю, что в этом случае также можно переместить _callback_ функции в соответствующие аргументы
```suggestion
const averageSalary = employees.reduce((acc, item) => acc + Number(item.salary), 0)/employees.length;
const sortedBySalary = employees.sort((a, b) => a.salary - b.salary);
const filterBySalaryAge = employees.filter(emp => emp.salary > 4500 && emp.age > 25);
```

2022-06-26 21:01 UTC, PonomareVlad commented on lesson_2/human.js
> +  },
Как можно учесть [кейс](https://thinknetica.ponomarevlad.ru/2/8.html?url=https%3A%2F%2Fraw.githubusercontent.com%2FAlyona-GS%2FJavaScript%2Flesson_2%2Flesson_2%2Fhuman.js#name), если у пользователя нет фамилии, и он вводит только имя ?

```js
human.fullName = 'Добби';
console.log(human.fullName); // Добби undefined
```

2022-06-26 21:01 UTC, PonomareVlad commented on lesson_2/human.js
> +  }
Проверьте, [в каком формате](https://thinknetica.ponomarevlad.ru/2/8.html?url=https%3A%2F%2Fraw.githubusercontent.com%2FAlyona-GS%2FJavaScript%2Flesson_2%2Flesson_2%2Fhuman.js#date-ru) функция поддерживает ввод даты и её вывод:

```js
human1.dateOfBirth = '01.01.2000';
console.log(human.dateOfBirth); // 1.1.2000
```

2022-06-27 10:51 UTC, Alyona-GS commented on lesson_2/compare_array.js
> +};
Да, возращает массив, содержащий результаты проверки сравнения (больше ли) элементов первого массива соответствующим элементам второго массива. В задании не было указано, к какому типу(или задаче) применять сравнение, поэтому сделала в общем виде.
По поводу применения (если я правильно поняла вопрос), в случае с массивами, состоящими из числовых значений - например, сравнение показателей среднемесячной температуры с прогнозируемыми значениями. Но в целом и для строковых массивов, и для массивов с булевыми значениями тоже подойдет.
Единственное что, не рассматривала обработку исключений (длина массивов, возможное несоответствие типов).

2022-06-27 11:13 UTC, Alyona-GS commented on lesson_2/employees.js
> +const filterBySalaryAge = employees.filter(filterCallBack);
Здесь получается на длину строки не смотреть?

2022-06-27 11:37 UTC, PonomareVlad commented on lesson_2/employees.js
> +const filterBySalaryAge = employees.filter(filterCallBack);
В таком вопросе лучше положиться на "объективные" факторы: количество повторных использований кода в противовес к количеству однострочных функций наполняющих область видимости (и блокирующих [GC](https://learn.javascript.ru/garbage-collection))

Замечу, что мое **предложение** базируется на принципе [YAGNI](https://ru.m.wikipedia.org/wiki/YAGNI) и не противоречит другим разумным принципам 🙂

2022-06-27 11:46 UTC, PonomareVlad commented on lesson_2/compare_array.js
> +};
Понял, благодарю, тогда в рамках этого задания решение выполнено корректно 👍🏻

2022-06-29 23:41 UTC, PonomareVlad approved these changes
Отлично 👍🏻

2022-07-01 10:50 UTC, merged